name: dahpc-2026
channels:
    - conda-forge
dependencies:
    - basemap
    - basemap-data-hires
    - geopandas
    - ipython
    - jupyter
    - jupyterlab
    - scipy
    - pandas
    - xlrd
    - sqlalchemy
    - seaborn
    - dask
    - graphviz
    - python-graphviz
    - scikit-learn
    - openpyxl
    - yfinance
